export interface CustomError extends Error {
  response?: {
    data?: {
      message?: string;
    };
  };
}

export interface UserProfileType {
  userId: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  fullName: string;
  tokenExpiration: string;
  role: string;
  companyId: number;
  token: string;
}

export interface StaffProfileTypes {
  staffId: number;
  firstName: string;
  surName: string;
  email: string;
  phoneNumber: string;
  isActive: boolean;
  imageUrl: string;
  fullName: string;
}

export interface claimsTypes {
  issuer: string;
  originalIssuer: string;
  properties: string;
  subject: string;
  type: string;
  value: string;
  valueType: string;
}

export type PackageProps = {
  amount: number;
  dateCreated: string;
  dateModified: string;
  duration: number;
  features: string;
  package: string;
  packageDetails: string;
  packageLogo: string | string;
  packagesId: number;
  userCreated: string;
  userModified: string;
};

export type CompanyDetail = {
  abn: string;
  companyAddress: string;
  companyDetails: string;
  companyEmail: string;
  companyHead: string;
  companyId: number;
  companyLogo: string;
  companyLogoFile: string;
  companyName: string;
  companyPhone: string;
  companyState: string;
  expirationDate: string | number;
  dateCreated: string;
  isApproved: boolean;
  autoRenewal: boolean;
  packages: {
    amount: number;
    dateCreated: string;
    duration: number;
    features: string;
    package: string;
    packageDetails: string;
    packageLogo: string;
    packagesId: number;
    userCreated: string;
  };
  signature: string;
  signatureFile: null;
  noOfUsers: number;
  packagesId: number;
  subscribtionDate: string;
  website: string;
  generalEmail: string;
  supportEmail: string;
  payrollEmail: string;
  providerNumber: string;
};

export type Refferal = {
  aboriginal_Torres: string;
  activity_group: string;
  aggression_History: string;
  allergies: string;
  behavior_Plan: string;
  clientReferralId: number;
  company: string;
  companyId: number;
  contactNumber: string;
  culturally_Linguistically: string;
  currentResidence: string;
  dateCreated: string;
  dateModified: string;
  de_escalation: string;
  dob: string;
  email: string;
  emergency_Contact: string;
  extra_Support: string;
  falls_Risk: string;
  fullName: string;
  gender: string;
  guardianDetails: string;
  illicit_Substances: string;
  isAccepted: boolean;
  lastName: string;
  lineItem: string;
  name: string;
  ndisEndDate: string;
  ndisGoals: string;
  ndisNo: string;
  ndisStartDate: string;
  nominatedCarer: string;
  participant_Engagement: string;
  participant_Interraction: string;
  participant_Providers: string;
  pets: string;
  physical_Illnesses: string;
  planManager: string;
  potential_Risk: string;
  providerTravel: string;
  psychiatric_Diagnosis: string;
  pto: string;
  public_Trustee: string;
  quote: string;
  referralCompany: string;
  referralEmail: string;
  referralFullName: string;
  referralLastName: string;
  referralName: string;
  referralPhone: string;
  referralSignature: string;
  referralSignatureFile: string;
  self_Harm: string;
  staff_Preference: string;
  supportCoordinator: string;
  support_Details: string;
  support_Holiday: string;
  support_Time: string;
  transport: string;
  triggers: string;
  ttpRate: string;
  unwell_Presentation: string;
  userCreated: string;
  userModified: string;
};

export type TimeSheet = {
  attendanceSplits: SplitedAttendance;
  staffTimeSheet: string;
  staff: boolean;
  client: boolean;
  totalDuration: number;
  totalAgreedDuration: number;
  totalAmount: number;
  normalDuration: number;
  eveningDuration: number;
  exceptionalDuration: number;
  satDuration: number;
  sunDuration: number;
  phDuration: number;
  totalKm: number;
  nightShift: number;
  staffName: string;
  fromDate: string;
  toDate: string;
  clientName: string;
  xeroUploadLink: string;
};

export type SplitedAttendance = {
  attendanceSplitId: number;
  staffId: number;
  staffName: string;
  clockIn: string;
  clockInCheck: boolean;
  clockOutCheck: boolean;
  clockOut: string;
  shiftId: number;
  duration: number;
  totalAgreedDuration: number;
  normalDuration: number;
  eveningDuration: number;
  exceptionalDuration: number;
  satDuration: number;
  sunDuration: number;
  phDuration: number;
  totalKm: number;
  totalDuration: number;
  shift: string;
  nightShift: number;
  companyID: number;
  dateCreated: string;
  userCreated: string;
  dateModified: string;
  userModified: string;
  shiftRoster: {
    shiftRosterId: number;
    staffId: number;
    dateFrom: string;
    dateTo: string;
    cancellationDate: string;
    activities: string;
    profileId: number;
    reason: string;
    clients: string;
    progressNoteId: number;
    status: string;
    appointment: string;
    attendance: boolean;
    requestCancellation: boolean;
    isNightShift: boolean;
    isCurrent: boolean;
    isEnded: boolean;
    isExceptionalShift: boolean;
    repeat: boolean;
    attendId: number;
    shift: string;
    companyID: number;
    dateCreated: string;
    userCreated: string;
    dateModified: string;
    userModified: string;
    profile: {
      profileId: number;
      firstName: string;
      surName: string;
      middleName: string;
      clientId: number;
      contactId: string;
      address: string;
      email: string;
      phoneNumber: string;
      gender: string;
      imageUrl: string;
      imageFile: string;
      country: string;
      state: string;
      city: string;
      isCompleted: boolean;
      isActive: boolean;
      dateOfBirth: string; // You may want to use Date type if it's a date string
      homePhone: string;
      workPhone: string;
      profession: string;
      culturalBackground: string;
      preferredLanguage: string;
      requireInterpreter: boolean;
      indigenousSatatus: string;
      ndisPlan: string;
      ndisPlanNote: string;
      privacyPreferences: string;
      financialArrangement: string;
      ndisNo: string;
      agreementStartDate: string; // You may want to use Date type if it's a date string
      agreementEndDate: string; // You may want to use Date type if it's a date string
      nextOfKin: string;
      relationship: string;
      kinPostcode: string;
      kinAddress: string;
      kinCountry: string;
      kinCity: string;
      kinEmail: string;
      suburb: string;
      kinState: string;
      kinPhoneNumber: string;
      fullName: string;
      dateCreated: string; // You may want to use Date type if it's a date string
      userCreated: string;
      dateModified: string; // You may want to use Date type if it's a date string
      userModified: string;
    };
    staff: {
      staffId: number;
      maxStaffId: string;
      firstName: string;
      surName: string;
      middleName: string;
      aboutMe: string;
      address: string;
      postcode: string;
      email: string;
      employeeId: string;
      phoneNumber: string;
      profession: string;
      gender: string;
      imageUrl: string;
      imageFile: string;
      country: string;
      state: string;
      city: string;
      isCompleted: boolean;
      isActive: boolean;
      dateOfBirth: string; // You may want to use Date type if it's a date string
      facebook: string;
      twitter: string;
      instagram: string;
      youtube: string;
      linkedIn: string;
      github: string;
      employmentType: string;
      taxFile: string;
      position: string;
      australianCitizen: boolean;
      dateJoined: string; // You may want to use Date type if it's a date string
      salary: number;
      payDay: number;
      payRate: string;
      bankName: string;
      bsb: string;
      branch: string;
      accountName: string;
      accountNumber: string;
      nextOfKin: string;
      relationship: string;
      kinPostcode: string;
      kinAddress: string;
      kinCountry: string;
      kinCity: string;
      kinEmail: string;
      suburb: string;
      kinState: string;
      kinPhoneNumber: string;
      isDocumentUploaded: boolean;
      isAdmin: boolean;
      adm_DesignationsId: number;
      adm_Designations: string; // You may want to define a type for this
      offerLetter: string;
      handbook: string;
      superForm: string;
      supportPosition: string;
      fullName: string;
      dateCreated: string; // You may want to use Date type if it's a date string
      userCreated: string;
      dateModified: string; // You may want to use Date type if it's a date string
      userModified: string;
    };
  };
};

export interface ClientDataRow {
  profileId: number;
  firstName: string;
  surName: string;
  middleName: string;
  clientId: number;
  contactId: string;
  address: string;
  email: string;
  phoneNumber: string;
  gender: string;
  imageUrl: string;
  imageFile: string;
  country: string;
  state: string;
  city: string;
  isActive: boolean;
  auditApproved: boolean;
  dateOfBirth: string;
  culturalBackground: string;
  preferredLanguage: string;
  requireInterpreter: boolean;
  indigenousSatatus: string;
  ndisPlan: string;
  privacyPreferences: string;
  financialArrangement: string;
  ndisNo: string;
  referral: string;
  kinSuburb: string;
  careManager: string;
  agreementStartDate: string; // You may want to use Date type if it's a date string
  agreementEndDate: string; // You may want to use Date type if it's a date string
  nextOfKin: string;
  relationship: string;
  kinPostcode: string;
  kinAddress: string;
  kinCountry: string;
  kinCity: string;
  kinEmail: string;
  suburb: string;
  kinState: string;
  kinPhoneNumber: string;
  fullName: string;
  xerolink: string;
  ndisPlanNote: string;
  signature: string | null;
  signatureFile: string | null;
}

export interface AdminDataRow {
  accountName: string;
  accountNumber: number;
  address: string;
  administratorId: number;
  bankName: string;
  branch: string;
  bsb: string;
  city: string;
  companyId: number;
  country: string;
  dateCreated: string;
  dateModified: string;
  dateOfBirth: string;
  email: string;
  employmentType: string;
  facebook: string;
  firstName: string;
  fullName: string;
  gender: string;
  github: string;
  imageFile: string;
  imageUrl: string;
  instagram: string;
  isActive: boolean;
  kinAddress: string;
  kinCity: string;
  kinCountry: string;
  kinEmail: string;
  kinPhoneNumber: number;
  kinPostcode: string;
  kinState: string;
  linkedIn: string;
  maxStaffId: string;
  middleName: string;
  nextOfKin: string;
  offerLetter: string;
  payDay: number;
  payRate: number;
  phoneNumber: number;
  position: string;
  postcode: string;
  profession: string;
  relationship: string;
  salary: number;
  state: string;
  suburb: string;
  surName: string;
  taxFile: string;
  twitter: string;
  userCreated: string;
  userModified: string;
  youtube: string;
}
export type StaffProfile = {
  staffId: number;
  maxStaffId: string;
  firstName: string;
  surName: string;
  middleName: string;
  aboutMe: string;
  address: string;
  postcode: string | null;
  employeeId: string | null;
  email: string;
  phoneNumber: string;
  profession: string | null;
  gender: string;
  imageUrl: string;
  imageFile: string | null;
  country: string | null;
  state: string | null;
  city: string | null;
  isCompleted: boolean;
  isActive: boolean;
  auditApproved: boolean;
  dateOfBirth: string; // Use appropriate Date type or string
  facebook: string | null;
  twitter: string | null;
  instagram: string | null;
  youtube: string | null;
  linkedIn: string | null;
  github: string | null;
  employmentType: string | null;
  taxFile: string | null;
  position: string | null;
  level: string;
  australianCitizen: boolean | null;
  dateJoined: string | null; // Use appropriate Date type or string
  salary: number;
  payDay: number;
  payRate: number | null;
  bankName: string | null;
  bsb: string | null;
  branch: string | null;
  accountName: string | null;
  accountNumber: string | null;
  nextOfKin: string;
  relationship: string;
  kinPostcode: string | null;
  kinAddress: string;
  kinCountry: string;
  kinCity: string | null;
  kinEmail: string | null;
  suburb: string | null;
  kinState: string;
  kinPhoneNumber: string | null;
  isDocumentUploaded: boolean;
  isAdmin: boolean;
  adm_DesignationsId: number | null;
  adm_Designations: string | null;
  offerLetter: string | null;
  handbook: string | null;
  superForm: string | null;
  supportPosition: string | null;
  companyId: number;
  company: string | null;
  xerolink: string;
  fullName: string;
  dateCreated: string; // Use appropriate Date type or string
  userCreated: string | null;
  dateModified: string; // Use appropriate Date type or string
  userModified: string | null;
  signatureUrl: string | null;
  signatureFile: string | null;
};
